"""empty message

Revision ID: cb8627a3103d
Revises: 
Create Date: 2025-01-25 23:49:10.552745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8627a3103d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), server_default='anonymous', nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('api_key')
    )
    op.create_table('image',
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('api_key')
    # ### end Alembic commands ###
